### PR TITLE
Create a small tutorial for suave.io on Azure

### PR DESCRIPTION
**Pull request by forki**
I reproduced your deployment and documented it in the readme.

It works like a charme!

works

### CODE REVIEW

**Comment by dsyme** [comment]
Could you also submit links to this at https://github.com/SuaveIO/suave please?   Thanks!

BTW my son said today "could we do some more work on our website on the weekend?" I replied "you bet, we'll take Suave on Azure for a spin!"

**Comment by forki** [comment]
Will do. 

One interesting thing is that FAKE is a bit overkill here at the moment. The syncing part (where FAKE would shine) is done by kudu sync. FAKE is only used as an fsi replacement to host suave at the moment (since there is no fsi on nuget). But of course that might change in the future and fake could be used instead of kudu sync. This would allow to remove dependency on node and npm (which AFAIK are only used to copy files).

**Comment by dsyme** [comment]
I see, got it.  BTW if you need to make an "F# Tools" package on nuget from the http://github.com/fsharp/fsharp bits for F# 3.1 I reckon you could do that - if you do, submit the packaging machinery to http://github.com/fsharp/fsharp alongside that used for the FSharp.Core packages. thx

**Comment by forki** [comment]
yeah. I don't think I will do this right now. Instead I plan to create a real build script here.

**Pull request merged**
